spring.application.name=balance-service-v2

# Perfil activo por defecto. En Docker se sobreescribe con SPRING_PROFILES_ACTIVE=prod
spring.profiles.active=local

# DataSource — usa variables de entorno si existen, sino usa NeonDB DEV como default
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-red-water-ac3dna23-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_jYfKb0RcnV8P}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka deshabilitado
eureka.client.enabled=false

# Keycloak Admin API — credenciales para gestión de usuarios
keycloak.admin.url=${KEYCLOAK_URL:http://62.171.160.238:8095}
keycloak.admin.realm=${KEYCLOAK_REALM:proyecto-h-dev}
keycloak.admin.username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:GeronimoAdmin2024!}

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.web.filter=DEBUG
