
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=balance-service-v2

# Deshabilitar Eureka (no se usa en v2)
eureka.client.enabled=false

# Definir el perfil por defecto (se sobrescribirá con la variable de entorno)
spring.profiles.active=prod

# Niveles de logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.web.filter=DEBUG

