spring.application.name=balance-service-v2

# Perfil activo por defecto. En Docker se sobreescribe con SPRING_PROFILES_ACTIVE=prod
spring.profiles.active=local

# DataSource — usa variables de entorno si existen, sino usa NeonDB DEV como default
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-red-water-ac3dna23-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_jYfKb0RcnV8P}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka deshabilitado
eureka.client.enabled=false

# Keycloak Admin API — credenciales para gestión de usuarios
keycloak.admin.url=${KEYCLOAK_URL:http://62.171.160.238:8095}
keycloak.admin.realm=${KEYCLOAK_REALM:proyecto-h-dev}
keycloak.admin.username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:GeronimoAdmin2024!}


# Cloudflare R2 — storage de comprobantes
r2.account-id=${R2_ACCOUNT_ID:2ba39b159cf1f47b7cc930696337e7ad}
r2.access-key=${R2_ACCESS_KEY_ID:3ec510ee84a7646caba1b9b9c08cdd4d}
r2.secret-key=${R2_SECRET_ACCESS_KEY:e3fb7fdf59141f022ed554a2b5662c29804f2e2ffb455527a8d50ca4254fe89a}
r2.bucket=${R2_BUCKET_NAME:humberto-comprobantes}
r2.endpoint=${R2_ENDPOINT:https://2ba39b159cf1f47b7cc930696337e7ad.r2.cloudflarestorage.com}
r2.public-url=${R2_PUBLIC_URL:https://pub-7e31005d201d4d34894758b2b1d00d9a.r2.dev}
r2.folder-prefix=${R2_FOLDER_PREFIX:local}

# Multipart — permitir uploads de hasta 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.web.filter=DEBUG
